FROM balenalib/%%BALENA_MACHINE_NAME%%-node:10-stretch-run

WORKDIR /usr/src/app

COPY package.json package.json
COPY package-lock.json package-lock.json
RUN JOBS=MAX npm ci --unsafe-perm && npm cache verify && rm -rf /tmp/*
COPY . ./

ENV UDEV=1

# CMD ["npm", "run", "start:remote"]
CMD ["npm", "start"]